### ISSUE TITLE
pip install threatconnect fails on centos 6

### ISSUE THREAD

**Issue by drawsmcgraw** [ThreatConnect-Inc/threatconnect-python#40]
TL;DR - 

1) 
`setup.py`, line 16, needs to change this:
```
download_url='https://github.com/ThreatConnect-Inc/threatconnect-python/tarball/{}'.format(version),
```

to this:
```
download_url='https://github.com/ThreatConnect-Inc/threatconnect-python/tarball/{0}'.format(version)
```

2)

`enum` needs to be a hard dependency, as `threatconnect` fails to import in Python without it, despite a successful install.

Output :

```
[root@threatconnect-01 centos]# pip install threatconnect
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting threatconnect
  Using cached threatconnect-2.4.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-PpfQz5/threatconnect/setup.py", line 16, in <module>
        download_url='https://github.com/ThreatConnect-Inc/threatconnect-python/tarball/{}'.format(version),
    ValueError: zero length field name in format
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-PpfQz5/threatconnect/
[root@threatconnect-01 centos]# 
```

Version details
```
[root@threatconnect-01 centos]# python -c "import requests; print requests.__version__"
2.13.0

[root@threatconnect-01 centos]# python --version
Python 2.6.6

[root@threatconnect-01 centos]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
```

And just to be certain, I get the same behavior when installing manually:
```
[root@threatconnect-01 threatconnect-python-2.4.16]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    download_url='https://github.com/ThreatConnect-Inc/threatconnect-python/tarball/{}'.format(version),
ValueError: zero length field name in format
```

After fixing the `format` issue in `setup.py`, the install succeeds. However, I hit an unmet dependency:

```
[root@threatconnect-01 threatconnect-python-2.4.16]# python -c "import threatconnect; print threatconnect.__version__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "threatconnect/__init__.py", line 7, in <module>
    from ThreatConnect import ThreatConnect, create_tc_arg_parser
  File "threatconnect/ThreatConnect.py", line 25, in <module>
    from ErrorCodes import ErrorCodes
  File "threatconnect/ErrorCodes.py", line 1, in <module>
    from enum import Enum
ImportError: No module named enum
```

A quick `pip install enum` fixes this issue and:

```
[root@threatconnect-01 threatconnect-python-2.4.16]# python -c "import threatconnect; print threatconnect.__version__"
2.4.16
```

I'm working on a PR right now. Hoping to get it filed today.

**Comment by fhightower** [comment]
With regards to the `ImportError: No module named enum` error, you will want to install [enum34](https://pypi.python.org/pypi/enum34) rather than just enum: `pip install enum34`.

This import exists in the [setup.py](https://github.com/ThreatConnect-Inc/threatconnect-python/blob/master/setup.py#L23), but only for python version 2.7, so good find.

**Comment by drawsmcgraw** [comment]
@fhightower Thanks for the quick response!

re: `enum`, The fix we're working through has the following update to `setup.py`:

```
@@ -24,7 +24,8 @@
     },
     install_requires=[
         'requests==2.13.0',
-        'python-dateutil==2.6.0'
+        'python-dateutil==2.6.0',
+        'enum==0.4.6'
     ],
     license = 'Apache License, Version 2',
     name='threatconnect',
```

We're just adding it into the `install_requires` section, which I imagine does not have the same effect as a `pip install enum34` would. 

I'm fine with changing it on our side or just abdicating to your team once we file our PR in its current state. Whichever is best for y'all.

**Comment by drawsmcgraw** [comment]
fwiw, we *did* have another entry for python 2.6 ([as you linked to](https://github.com/ThreatConnect-Inc/threatconnect-python/blob/master/setup.py#L23)) but we still got the `ImportError` with that approach. Hence the heavy-handed approach with the `install_requires` section.

**Comment by fhightower** [comment]
Interesting, that's strange. I'll mess around with it and see what is going on.

**Comment by bcsummers** [comment]
I added an update in the develop branch that should fix the reported issues.  If you have a second to test it out that would be great.  I'll do a bit more testing in other versions to ensure nothing is off before releasing.

https://github.com/ThreatConnect-Inc/threatconnect-python/blob/develop/setup.py

**Comment by fhightower** [comment]
@bcsummers : Was this issue fixed with https://github.com/ThreatConnect-Inc/threatconnect-python/releases/tag/2.4.17 ?
